### ISSUE TITLE
Offering this in Homebrew?

### ISSUE THREAD

**Issue by chamini2** [jcostom/maclock#2]
it would be awesome to automate installation by enabling

```
$ brew install maclock
```

**Comment by jcostom** [comment]
I tried. There just wasn't the interest in doing it.  I did setup a personal tap, which you're free to take advantage of.

`brew tap jcostom/taps`

then `brew install maclock`

FWIW, once you're on macOS 11, everything works the way you'd expect, which is what drove me to do this in the first place.
